apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebs-metrics-reconciler
  labels:
    app.kubernetes.io/name: ebs-metrics-reconciler
    app.kubernetes.io/part-of: ebs-metrics-exporter
  annotations:
    package-operator.run/phase: rbac
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
