apiVersion: v1
kind: Namespace
metadata:
  name: openshift-sre-ebs-metrics
  annotations:
    package-operator.run/phase: namespace
    package-operator.run/collision-protection: IfNoController
    openshift.io/cluster-monitoring: "true"
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
