apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: ebs-metrics-exporter
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
    kubernetes.io/description: |
      SCC for EBS metrics exporter DaemonSet. Grants privileged access
      to NVMe devices for IOCTL operations.
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: true
allowHostPorts: false
allowPrivilegedContainer: true
allowPrivilegeEscalation: true
allowedCapabilities:
- SYS_ADMIN
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:openshift-sre-ebs-metrics:ebs-metrics-exporter
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- persistentVolumeClaim
- projected
- secret
