apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-metrics-exporter
  namespace: openshift-sre-ebs-metrics
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
