# This file is generated by boilerplate/update. Do not edit directly.
# Run 'make boilerplate-update' to regenerate this file.

# Placeholder - will be populated when boilerplate/update is run
# For now, this allows the Makefile to function

# Include project-specific configuration
-include project.mk

# Basic build targets until boilerplate is fully initialized
.PHONY: go-build
go-build:
	@echo "Building operator..."
	CGO_ENABLED=0 go build -o bin/ebs-metrics-exporter-operator main.go
	@echo "Build complete: bin/ebs-metrics-exporter-operator"

.PHONY: go-test
go-test:
	go test ./...

.PHONY: go-fmt
go-fmt:
	go fmt ./...

.PHONY: go-vet
go-vet:
	go vet ./...

.PHONY: test
test: go-test

.PHONY: lint
lint: go-vet

.PHONY: coverage
coverage:
	go test -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out -o coverage.html

# Placeholder targets that will be replaced by boilerplate
.PHONY: generate
generate:
	@echo "Run 'make boilerplate-update' to get full boilerplate functionality"

.PHONY: validate
validate:
	@echo "Run 'make boilerplate-update' to get full boilerplate functionality"
